=== uo295432/sew/xml/circuito.dtd
<!ELEMENT circuito (nombre,longitudTotal,anchuraMedia,fecha,hora,vueltas,localidad,país,referencias,fotografías,vídeos,coordenadas,tramos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitudTotal (#PCDATA)>
<!ELEMENT anchuraMedia (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT país (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT fotografías (fotografía+)>
<!ELEMENT fotografía (#PCDATA)>
<!ELEMENT vídeos (vídeo*)>
<!ELEMENT vídeo (#PCDATA)>
<!ELEMENT coordenadas (longitud,latitud,altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT tramos (tramo*)>
<!ELEMENT tramo (distancia,coordenadas,sector)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT sector (#PCDATA)>
<!ATTLIST longitudTotal 
	unidad CDATA #REQUIRED>
<!ATTLIST anchuraMedia
	unidad CDATA #REQUIRED>
<!ATTLIST fotografía
	descripción CDATA #REQUIRED>
<!ATTLIST vídeo
    descripción CDATA #REQUIRED>
<!ATTLIST distancia
	unidad CDATA #REQUIRED>

=== uo295432/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombre>
        Bakú City
    </nombre>
    <longitudTotal unidad="km">
        6,003
    </longitudTotal>
    <anchuraMedia unidad="m">
        Entre 13 en las partes más anchas y 7,5 en las más estrechas
    </anchuraMedia>
    <fecha>
        15 de Septiembre de 2024
    </fecha>
    <hora>
        13:00
    </hora>
    <vueltas>
        51
    </vueltas>
    <localidad>
        Bakú
    </localidad>
    <país>
        Azerbaiyán
    </país>
    <referencias>
        <referencia>https://es.wikipedia.org/wiki/Circuito_callejero_de_Bak%C3%BA</referencia>
        <referencia>https://www.circuitosdecarreras.com/azerbaiyan/circuito-callejero-baku/</referencia>
        <referencia>https://www.elmundo.es/deportes/formula-1/2023/04/29/6448fa26e4d4d80a1c8b45c2.html</referencia>
    </referencias>
    <fotografías>
        <fotografía descripción="Foto del circuito con un castillo de fondo">castillo.jpg</fotografía>
    </fotografías>
    <vídeos>

    </vídeos>
    <coordenadas>
        <longitud>49,8495924</longitud>
        <latitud>40,3718316</latitud>
        <altitud>-0,2889786</altitud>
    </coordenadas>
    <tramos>
        <tramo>
            <distancia unidad="m">499,3</distancia>
            <coordenadas>
                <longitud>49,8545557</longitud>
                <latitud>40,3731892</latitud>
                <altitud>-0,5166922</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">336,77</distancia>
            <coordenadas>
                <longitud>49,8529110</longitud>
                <latitud>40,3749174</latitud>
                <altitud>-0,6408335</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">604,9</distancia>
            <coordenadas>
                <longitud>49,8479050</longitud>
                <latitud>40,3734439</latitud>
                <altitud>-0,8064461</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">222,62</distancia>
            <coordenadas>
                <longitud>49,8475531</longitud>
                <latitud>40,3719633</latitud>
                <altitud>-0,5166671</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">431,93</distancia>
            <coordenadas>
                <longitud>49,8450937</longitud>
                <latitud>40,3707944</latitud>
                <altitud>-0,8065115</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">139,76</distancia>
            <coordenadas>
                <longitud>49,8428731</longitud>
                <latitud>40,3698059</latitud>
                <altitud>-0,8070206</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">31,17</distancia>
            <coordenadas>
                <longitud>49,8428731</longitud>
                <latitud>40,3698059</latitud>
                <altitud>-0,8070206</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">57,08</distancia>
            <coordenadas>
                <longitud>49,8428731</longitud>
                <latitud>40,3698059</latitud>
                <altitud>-0,8070206</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">394,64</distancia>
            <coordenadas>
                <longitud>49,8395937</longitud>
                <latitud>40,3680318</latitud>
                <altitud>-0,8064940</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">206,04</distancia>
            <coordenadas>
                <longitud>49,8373969</longitud>
                <latitud>40,3683378</latitud>
                <altitud>-0,5167021</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">21,18</distancia>
            <coordenadas>
                <longitud>49,8373969</longitud>
                <latitud>40,3683378</latitud>
                <altitud>-0,5167021</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">27,2</distancia>
            <coordenadas>
                <longitud>49,8373969</longitud>
                <latitud>40,3683378</latitud>
                <altitud>-0,5167021</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">49,93</distancia>
            <coordenadas>
                <longitud>49,8367566</longitud>
                <latitud>40,3684335</latitud>
                <altitud>-0,5166372</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">67,55</distancia>
            <coordenadas>
                <longitud>49,8359340</longitud>
                <latitud>40,3689011</latitud>
                <altitud>-0,5167383</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">121,2</distancia>
            <coordenadas>
                <longitud>49,8334418</longitud>
                <latitud>40,3680403</latitud>
                <altitud>2,1271189</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">278</distancia>
            <coordenadas>
                <longitud>49,8326476</longitud>
                <latitud>40,3677363</latitud>
                <altitud>2,4244253</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">209,73</distancia>
            <coordenadas>
                <longitud>49,8329887</longitud>
                <latitud>40,3677244</latitud>
                <altitud>2,9066299</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">242,47</distancia>
            <coordenadas>
                <longitud>49,8331361</longitud>
                <latitud>40,3651472</latitud>
                <altitud>-0,1883513</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">315,34</distancia>
            <coordenadas>
                <longitud>49,8338012</longitud>
                <latitud>40,3632055</latitud>
                <altitud>-0,5167078</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">71,18</distancia>
            <coordenadas>
                <longitud>49,8338012</longitud>
                <latitud>40,3632055</latitud>
                <altitud>-0,5167078</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">63,26</distancia>
            <coordenadas>
                <longitud>49,8338012</longitud>
                <latitud>40,3632055</latitud>
                <altitud>-0,5167078</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">120,66</distancia>
            <coordenadas>
                <longitud>49,8346435</longitud>
                <latitud>40,3636762</latitud>
                <altitud>-0,5166895</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">234,59</distancia>
            <coordenadas>
                <longitud>49,8376975</longitud>
                <latitud>40,3655386</latitud>
                <altitud>-0,5107094</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">150,83</distancia>
            <coordenadas>
                <longitud>49,8375295</longitud>
                <latitud>40,3664137</latitud>
                <altitud>-0,5166841</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">381,72</distancia>
            <coordenadas>
                <longitud>49,8406040</longitud>
                <latitud>40,3680469</latitud>
                <altitud>-0,8065870</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="m">728,42</distancia>
            <coordenadas>
                <longitud>49,8495924</longitud>
                <latitud>40,3718316</latitud>
                <altitud>-0,2889786</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
    </tramos>
</circuito>
